# Generated by Django 3.0.2 on 2020-02-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_text',
            field=models.TextField(),
        ),
    ]
